language: node_js
node_js:
  - "0.12"
addons:
  postgresql: "9.4"
before_install:
  - npm install -g coffee-script grunt-cli istanbul mocha
install:
  - npm install
before_script:
  - grunt build
  - psql -c 'create database Karma;' -U postgres
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp ./config.travis.coffee ./config.coffee
script:
  - npm test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
notifications:
  slack:
    secure: EcTQgMgC4DnTXvphTy9QsSB+Ze2GCkEqy6lQ6P4Zb4s/jvvrp7R5N6UffaQ7L30nG4D1lxAwO7xo0LZ+JaMvGtnLhD5JDCJd00UMgaKrZAXXSDwIEtNlZyy5364TdwEF6TdbTuoGIQOWQN2KHntWiRvTFvl/yOHmZMDoQDkxXbR80HhFThVEVGUSbilGlz/4RHBK8h7n1bFRsIcete/gCsjHZk00ubFwIvGf4T37EoGHx6suUgQ4CiqGOXhn5qZc4da/qmf++YUEWaDZgHeFKsObMs628r6/ILTTYoVLXwrKT2OQRT54+RXezY51bPFrq00Ab23RG6WLeJfucn0kjPqnuPQXWyuUt4KqdQUaesGR8+lfw2bPh/tmCYS0p1x9ZtbV7x0ZNcx0TI2ifCgaMEPdQQTKfgYeJHK+nuO/gf+qi6SEmkKOEJXhPg16y1YaYqZ/ML3FWvCEdZa6JGV/cA70oIndxoH85+Zq5DOz88kgmiOC9+1zmkRzaTOS8SPqBmJLu/7YDlAv+ZOSpa00XdG7LqOxJoOFDPnqMNDeGW/wN0EjaOKSLLVBh8OnV8OKlq3iKXvKLLQ6IlNWcUsqoD4c7HCCEfP8U14u192y1eisfJ6qyHvIpmNFnFHuqfj5prmSuPw7cfTopmcFbyzjWCV5EycvuAXReZqZMGD68Uc=
